---
name: Linting

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Markdown
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: MarkdownLint-Cli
        run: make markdownlint
